// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: delegator_contract.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using System.Collections.Generic;
using aelf = global::AElf.CSharp.Core;

namespace AElf.Contracts.Delegator {

  #region Events
  #endregion
  public static partial class DelegatorContractContainer
  {
    static readonly string __ServiceName = "DelegatorContract";

    #region Marshallers
    static readonly aelf::Marshaller<global::AElf.Contracts.Delegator.RegisterSendersInput> __Marshaller_RegisterSendersInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.Delegator.RegisterSendersInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.Delegator.RegisterMethodsInput> __Marshaller_RegisterMethodsInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.Delegator.RegisterMethodsInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.Delegator.ForwardInput> __Marshaller_ForwardInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.Delegator.ForwardInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Types.Hash> __Marshaller_aelf_Hash = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Types.Hash.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.Delegator.IsPermittedAddressInput> __Marshaller_IsPermittedAddressInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.Delegator.IsPermittedAddressInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.BoolValue> __Marshaller_google_protobuf_BoolValue = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.BoolValue.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.Delegator.IsPermittedMethodInput> __Marshaller_IsPermittedMethodInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.Delegator.IsPermittedMethodInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.Delegator.ForwardRecord> __Marshaller_ForwardRecord = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.Delegator.ForwardRecord.Parser.ParseFrom);
    #endregion

    #region Methods
    static readonly aelf::Method<global::AElf.Contracts.Delegator.RegisterSendersInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RegisterSenders = new aelf::Method<global::AElf.Contracts.Delegator.RegisterSendersInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "RegisterSenders",
        __Marshaller_RegisterSendersInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.Delegator.RegisterMethodsInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RegisterMethods = new aelf::Method<global::AElf.Contracts.Delegator.RegisterMethodsInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "RegisterMethods",
        __Marshaller_RegisterMethodsInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.Delegator.ForwardInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Forward = new aelf::Method<global::AElf.Contracts.Delegator.ForwardInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Forward",
        __Marshaller_ForwardInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Types.Hash, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ForwardCheck = new aelf::Method<global::AElf.Types.Hash, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "ForwardCheck",
        __Marshaller_aelf_Hash,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.Delegator.IsPermittedAddressInput, global::Google.Protobuf.WellKnownTypes.BoolValue> __Method_IsPermittedAddress = new aelf::Method<global::AElf.Contracts.Delegator.IsPermittedAddressInput, global::Google.Protobuf.WellKnownTypes.BoolValue>(
        aelf::MethodType.View,
        __ServiceName,
        "IsPermittedAddress",
        __Marshaller_IsPermittedAddressInput,
        __Marshaller_google_protobuf_BoolValue);

    static readonly aelf::Method<global::AElf.Contracts.Delegator.IsPermittedMethodInput, global::Google.Protobuf.WellKnownTypes.BoolValue> __Method_IsPermittedMethod = new aelf::Method<global::AElf.Contracts.Delegator.IsPermittedMethodInput, global::Google.Protobuf.WellKnownTypes.BoolValue>(
        aelf::MethodType.View,
        __ServiceName,
        "IsPermittedMethod",
        __Marshaller_IsPermittedMethodInput,
        __Marshaller_google_protobuf_BoolValue);

    static readonly aelf::Method<global::AElf.Types.Hash, global::AElf.Contracts.Delegator.ForwardRecord> __Method_GetForwardRecord = new aelf::Method<global::AElf.Types.Hash, global::AElf.Contracts.Delegator.ForwardRecord>(
        aelf::MethodType.View,
        __ServiceName,
        "GetForwardRecord",
        __Marshaller_aelf_Hash,
        __Marshaller_ForwardRecord);

    #endregion

    #region Descriptors
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::AElf.Contracts.Delegator.DelegatorContractReflection.Descriptor.Services[0]; }
    }

    public static global::System.Collections.Generic.IReadOnlyList<global::Google.Protobuf.Reflection.ServiceDescriptor> Descriptors
    {
      get
      {
        return new global::System.Collections.Generic.List<global::Google.Protobuf.Reflection.ServiceDescriptor>()
        {
          global::AElf.Contracts.Delegator.DelegatorContractReflection.Descriptor.Services[0],
        };
      }
    }
    #endregion
  }
}
#endregion

