// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: delegator_contract.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace AElf.Contracts.Delegator {

  /// <summary>Holder for reflection information generated from delegator_contract.proto</summary>
  public static partial class DelegatorContractReflection {

    #region Descriptor
    /// <summary>File descriptor for delegator_contract.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DelegatorContractReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhkZWxlZ2F0b3JfY29udHJhY3QucHJvdG8aD2FlbGYvY29yZS5wcm90bxoS",
            "YWVsZi9vcHRpb25zLnByb3RvGhtnb29nbGUvcHJvdG9idWYvZW1wdHkucHJv",
            "dG8aHmdvb2dsZS9wcm90b2J1Zi93cmFwcGVycy5wcm90byJfChRSZWdpc3Rl",
            "clNlbmRlcnNJbnB1dBIQCghzY29wZV9pZBgBIAEoCRIiCgxhZGRyZXNzX2xp",
            "c3QYAiABKAsyDC5BZGRyZXNzTGlzdBIRCglpc19yZW1vdmUYAyABKAgiYgoU",
            "UmVnaXN0ZXJNZXRob2RzSW5wdXQSEAoIc2NvcGVfaWQYASABKAkSJQoQbWV0",
            "aG9kX25hbWVfbGlzdBgCIAEoCzILLk1ldGhvZExpc3QSEQoJaXNfcmVtb3Zl",
            "GAMgASgIIisKC0FkZHJlc3NMaXN0EhwKBXZhbHVlGAEgAygLMg0uYWVsZi5B",
            "ZGRyZXNzIhsKCk1ldGhvZExpc3QSDQoFdmFsdWUYASADKAkifAoMRm9yd2Fy",
            "ZElucHV0Eg8KB2Zyb21faWQYASABKAkSIQoKdG9fYWRkcmVzcxgCIAEoCzIN",
            "LmFlbGYuQWRkcmVzcxITCgttZXRob2RfbmFtZRgDIAEoCRIRCglwYXJhbWV0",
            "ZXIYBCABKAwSEAoIc2NvcGVfaWQYBSABKAkiqgEKDUZvcndhcmRSZWNvcmQS",
            "DwoHZnJvbV9pZBgBIAEoCRIQCghzY29wZV9pZBgCIAEoCRIrChR2aXJ0dWFs",
            "X2Zyb21fYWRkcmVzcxgDIAEoCzINLmFlbGYuQWRkcmVzcxIhCgp0b19hZGRy",
            "ZXNzGAQgASgLMg0uYWVsZi5BZGRyZXNzEhMKC21ldGhvZF9uYW1lGAUgASgJ",
            "EhEKCXBhcmFtZXRlchgGIAEoDCJuChdJc1Blcm1pdHRlZEFkZHJlc3NJbnB1",
            "dBIhCgp0b19hZGRyZXNzGAEgASgLMg0uYWVsZi5BZGRyZXNzEhAKCHNjb3Bl",
            "X2lkGAIgASgJEh4KB2FkZHJlc3MYAyABKAsyDS5hZWxmLkFkZHJlc3MiYgoW",
            "SXNQZXJtaXR0ZWRNZXRob2RJbnB1dBIhCgp0b19hZGRyZXNzGAEgASgLMg0u",
            "YWVsZi5BZGRyZXNzEhAKCHNjb3BlX2lkGAIgASgJEhMKC21ldGhvZF9uYW1l",
            "GAMgASgJMv0DChFEZWxlZ2F0b3JDb250cmFjdBJCCg9SZWdpc3RlclNlbmRl",
            "cnMSFS5SZWdpc3RlclNlbmRlcnNJbnB1dBoWLmdvb2dsZS5wcm90b2J1Zi5F",
            "bXB0eSIAEkIKD1JlZ2lzdGVyTWV0aG9kcxIVLlJlZ2lzdGVyTWV0aG9kc0lu",
            "cHV0GhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5IgASMgoHRm9yd2FyZBINLkZv",
            "cndhcmRJbnB1dBoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eSIAEjQKDEZvcndh",
            "cmRDaGVjaxIKLmFlbGYuSGFzaBoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eSIA",
            "ElEKEklzUGVybWl0dGVkQWRkcmVzcxIYLklzUGVybWl0dGVkQWRkcmVzc0lu",
            "cHV0GhouZ29vZ2xlLnByb3RvYnVmLkJvb2xWYWx1ZSIFiIn3AQESTwoRSXNQ",
            "ZXJtaXR0ZWRNZXRob2QSFy5Jc1Blcm1pdHRlZE1ldGhvZElucHV0GhouZ29v",
            "Z2xlLnByb3RvYnVmLkJvb2xWYWx1ZSIFiIn3AQESNQoQR2V0Rm9yd2FyZFJl",
            "Y29yZBIKLmFlbGYuSGFzaBoOLkZvcndhcmRSZWNvcmQiBYiJ9wEBGhuyzPYB",
            "FkRlbGVnYXRvckNvbnRyYWN0U3RhdGVCG6oCGEFFbGYuQ29udHJhY3RzLkRl",
            "bGVnYXRvcmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::AElf.Types.CoreReflection.Descriptor, global::AElf.OptionsReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.WrappersReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::AElf.Contracts.Delegator.RegisterSendersInput), global::AElf.Contracts.Delegator.RegisterSendersInput.Parser, new[]{ "ScopeId", "AddressList", "IsRemove" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AElf.Contracts.Delegator.RegisterMethodsInput), global::AElf.Contracts.Delegator.RegisterMethodsInput.Parser, new[]{ "ScopeId", "MethodNameList", "IsRemove" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AElf.Contracts.Delegator.AddressList), global::AElf.Contracts.Delegator.AddressList.Parser, new[]{ "Value" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AElf.Contracts.Delegator.MethodList), global::AElf.Contracts.Delegator.MethodList.Parser, new[]{ "Value" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AElf.Contracts.Delegator.ForwardInput), global::AElf.Contracts.Delegator.ForwardInput.Parser, new[]{ "FromId", "ToAddress", "MethodName", "Parameter", "ScopeId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AElf.Contracts.Delegator.ForwardRecord), global::AElf.Contracts.Delegator.ForwardRecord.Parser, new[]{ "FromId", "ScopeId", "VirtualFromAddress", "ToAddress", "MethodName", "Parameter" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AElf.Contracts.Delegator.IsPermittedAddressInput), global::AElf.Contracts.Delegator.IsPermittedAddressInput.Parser, new[]{ "ToAddress", "ScopeId", "Address" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AElf.Contracts.Delegator.IsPermittedMethodInput), global::AElf.Contracts.Delegator.IsPermittedMethodInput.Parser, new[]{ "ToAddress", "ScopeId", "MethodName" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class RegisterSendersInput : pb::IMessage<RegisterSendersInput>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RegisterSendersInput> _parser = new pb::MessageParser<RegisterSendersInput>(() => new RegisterSendersInput());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RegisterSendersInput> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AElf.Contracts.Delegator.DelegatorContractReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RegisterSendersInput() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RegisterSendersInput(RegisterSendersInput other) : this() {
      scopeId_ = other.scopeId_;
      addressList_ = other.addressList_ != null ? other.addressList_.Clone() : null;
      isRemove_ = other.isRemove_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RegisterSendersInput Clone() {
      return new RegisterSendersInput(this);
    }

    /// <summary>Field number for the "scope_id" field.</summary>
    public const int ScopeIdFieldNumber = 1;
    private string scopeId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ScopeId {
      get { return scopeId_; }
      set {
        scopeId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "address_list" field.</summary>
    public const int AddressListFieldNumber = 2;
    private global::AElf.Contracts.Delegator.AddressList addressList_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AElf.Contracts.Delegator.AddressList AddressList {
      get { return addressList_; }
      set {
        addressList_ = value;
      }
    }

    /// <summary>Field number for the "is_remove" field.</summary>
    public const int IsRemoveFieldNumber = 3;
    private bool isRemove_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsRemove {
      get { return isRemove_; }
      set {
        isRemove_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RegisterSendersInput);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RegisterSendersInput other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ScopeId != other.ScopeId) return false;
      if (!object.Equals(AddressList, other.AddressList)) return false;
      if (IsRemove != other.IsRemove) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ScopeId.Length != 0) hash ^= ScopeId.GetHashCode();
      if (addressList_ != null) hash ^= AddressList.GetHashCode();
      if (IsRemove != false) hash ^= IsRemove.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ScopeId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ScopeId);
      }
      if (addressList_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(AddressList);
      }
      if (IsRemove != false) {
        output.WriteRawTag(24);
        output.WriteBool(IsRemove);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ScopeId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ScopeId);
      }
      if (addressList_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(AddressList);
      }
      if (IsRemove != false) {
        output.WriteRawTag(24);
        output.WriteBool(IsRemove);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ScopeId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ScopeId);
      }
      if (addressList_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AddressList);
      }
      if (IsRemove != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RegisterSendersInput other) {
      if (other == null) {
        return;
      }
      if (other.ScopeId.Length != 0) {
        ScopeId = other.ScopeId;
      }
      if (other.addressList_ != null) {
        if (addressList_ == null) {
          AddressList = new global::AElf.Contracts.Delegator.AddressList();
        }
        AddressList.MergeFrom(other.AddressList);
      }
      if (other.IsRemove != false) {
        IsRemove = other.IsRemove;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ScopeId = input.ReadString();
            break;
          }
          case 18: {
            if (addressList_ == null) {
              AddressList = new global::AElf.Contracts.Delegator.AddressList();
            }
            input.ReadMessage(AddressList);
            break;
          }
          case 24: {
            IsRemove = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ScopeId = input.ReadString();
            break;
          }
          case 18: {
            if (addressList_ == null) {
              AddressList = new global::AElf.Contracts.Delegator.AddressList();
            }
            input.ReadMessage(AddressList);
            break;
          }
          case 24: {
            IsRemove = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class RegisterMethodsInput : pb::IMessage<RegisterMethodsInput>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RegisterMethodsInput> _parser = new pb::MessageParser<RegisterMethodsInput>(() => new RegisterMethodsInput());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RegisterMethodsInput> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AElf.Contracts.Delegator.DelegatorContractReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RegisterMethodsInput() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RegisterMethodsInput(RegisterMethodsInput other) : this() {
      scopeId_ = other.scopeId_;
      methodNameList_ = other.methodNameList_ != null ? other.methodNameList_.Clone() : null;
      isRemove_ = other.isRemove_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RegisterMethodsInput Clone() {
      return new RegisterMethodsInput(this);
    }

    /// <summary>Field number for the "scope_id" field.</summary>
    public const int ScopeIdFieldNumber = 1;
    private string scopeId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ScopeId {
      get { return scopeId_; }
      set {
        scopeId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "method_name_list" field.</summary>
    public const int MethodNameListFieldNumber = 2;
    private global::AElf.Contracts.Delegator.MethodList methodNameList_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AElf.Contracts.Delegator.MethodList MethodNameList {
      get { return methodNameList_; }
      set {
        methodNameList_ = value;
      }
    }

    /// <summary>Field number for the "is_remove" field.</summary>
    public const int IsRemoveFieldNumber = 3;
    private bool isRemove_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsRemove {
      get { return isRemove_; }
      set {
        isRemove_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RegisterMethodsInput);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RegisterMethodsInput other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ScopeId != other.ScopeId) return false;
      if (!object.Equals(MethodNameList, other.MethodNameList)) return false;
      if (IsRemove != other.IsRemove) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ScopeId.Length != 0) hash ^= ScopeId.GetHashCode();
      if (methodNameList_ != null) hash ^= MethodNameList.GetHashCode();
      if (IsRemove != false) hash ^= IsRemove.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ScopeId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ScopeId);
      }
      if (methodNameList_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(MethodNameList);
      }
      if (IsRemove != false) {
        output.WriteRawTag(24);
        output.WriteBool(IsRemove);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ScopeId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ScopeId);
      }
      if (methodNameList_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(MethodNameList);
      }
      if (IsRemove != false) {
        output.WriteRawTag(24);
        output.WriteBool(IsRemove);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ScopeId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ScopeId);
      }
      if (methodNameList_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MethodNameList);
      }
      if (IsRemove != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RegisterMethodsInput other) {
      if (other == null) {
        return;
      }
      if (other.ScopeId.Length != 0) {
        ScopeId = other.ScopeId;
      }
      if (other.methodNameList_ != null) {
        if (methodNameList_ == null) {
          MethodNameList = new global::AElf.Contracts.Delegator.MethodList();
        }
        MethodNameList.MergeFrom(other.MethodNameList);
      }
      if (other.IsRemove != false) {
        IsRemove = other.IsRemove;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ScopeId = input.ReadString();
            break;
          }
          case 18: {
            if (methodNameList_ == null) {
              MethodNameList = new global::AElf.Contracts.Delegator.MethodList();
            }
            input.ReadMessage(MethodNameList);
            break;
          }
          case 24: {
            IsRemove = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ScopeId = input.ReadString();
            break;
          }
          case 18: {
            if (methodNameList_ == null) {
              MethodNameList = new global::AElf.Contracts.Delegator.MethodList();
            }
            input.ReadMessage(MethodNameList);
            break;
          }
          case 24: {
            IsRemove = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class AddressList : pb::IMessage<AddressList>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AddressList> _parser = new pb::MessageParser<AddressList>(() => new AddressList());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AddressList> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AElf.Contracts.Delegator.DelegatorContractReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AddressList() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AddressList(AddressList other) : this() {
      value_ = other.value_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AddressList Clone() {
      return new AddressList(this);
    }

    /// <summary>Field number for the "value" field.</summary>
    public const int ValueFieldNumber = 1;
    private static readonly pb::FieldCodec<global::AElf.Types.Address> _repeated_value_codec
        = pb::FieldCodec.ForMessage(10, global::AElf.Types.Address.Parser);
    private readonly pbc::RepeatedField<global::AElf.Types.Address> value_ = new pbc::RepeatedField<global::AElf.Types.Address>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::AElf.Types.Address> Value {
      get { return value_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AddressList);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AddressList other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!value_.Equals(other.value_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= value_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      value_.WriteTo(output, _repeated_value_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      value_.WriteTo(ref output, _repeated_value_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += value_.CalculateSize(_repeated_value_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AddressList other) {
      if (other == null) {
        return;
      }
      value_.Add(other.value_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            value_.AddEntriesFrom(input, _repeated_value_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            value_.AddEntriesFrom(ref input, _repeated_value_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class MethodList : pb::IMessage<MethodList>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MethodList> _parser = new pb::MessageParser<MethodList>(() => new MethodList());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MethodList> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AElf.Contracts.Delegator.DelegatorContractReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MethodList() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MethodList(MethodList other) : this() {
      value_ = other.value_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MethodList Clone() {
      return new MethodList(this);
    }

    /// <summary>Field number for the "value" field.</summary>
    public const int ValueFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_value_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> value_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> Value {
      get { return value_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MethodList);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MethodList other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!value_.Equals(other.value_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= value_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      value_.WriteTo(output, _repeated_value_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      value_.WriteTo(ref output, _repeated_value_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += value_.CalculateSize(_repeated_value_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MethodList other) {
      if (other == null) {
        return;
      }
      value_.Add(other.value_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            value_.AddEntriesFrom(input, _repeated_value_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            value_.AddEntriesFrom(ref input, _repeated_value_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ForwardInput : pb::IMessage<ForwardInput>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ForwardInput> _parser = new pb::MessageParser<ForwardInput>(() => new ForwardInput());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ForwardInput> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AElf.Contracts.Delegator.DelegatorContractReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ForwardInput() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ForwardInput(ForwardInput other) : this() {
      fromId_ = other.fromId_;
      toAddress_ = other.toAddress_ != null ? other.toAddress_.Clone() : null;
      methodName_ = other.methodName_;
      parameter_ = other.parameter_;
      scopeId_ = other.scopeId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ForwardInput Clone() {
      return new ForwardInput(this);
    }

    /// <summary>Field number for the "from_id" field.</summary>
    public const int FromIdFieldNumber = 1;
    private string fromId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FromId {
      get { return fromId_; }
      set {
        fromId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "to_address" field.</summary>
    public const int ToAddressFieldNumber = 2;
    private global::AElf.Types.Address toAddress_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AElf.Types.Address ToAddress {
      get { return toAddress_; }
      set {
        toAddress_ = value;
      }
    }

    /// <summary>Field number for the "method_name" field.</summary>
    public const int MethodNameFieldNumber = 3;
    private string methodName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MethodName {
      get { return methodName_; }
      set {
        methodName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "parameter" field.</summary>
    public const int ParameterFieldNumber = 4;
    private pb::ByteString parameter_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Parameter {
      get { return parameter_; }
      set {
        parameter_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "scope_id" field.</summary>
    public const int ScopeIdFieldNumber = 5;
    private string scopeId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ScopeId {
      get { return scopeId_; }
      set {
        scopeId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ForwardInput);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ForwardInput other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FromId != other.FromId) return false;
      if (!object.Equals(ToAddress, other.ToAddress)) return false;
      if (MethodName != other.MethodName) return false;
      if (Parameter != other.Parameter) return false;
      if (ScopeId != other.ScopeId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (FromId.Length != 0) hash ^= FromId.GetHashCode();
      if (toAddress_ != null) hash ^= ToAddress.GetHashCode();
      if (MethodName.Length != 0) hash ^= MethodName.GetHashCode();
      if (Parameter.Length != 0) hash ^= Parameter.GetHashCode();
      if (ScopeId.Length != 0) hash ^= ScopeId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (FromId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(FromId);
      }
      if (toAddress_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ToAddress);
      }
      if (MethodName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(MethodName);
      }
      if (Parameter.Length != 0) {
        output.WriteRawTag(34);
        output.WriteBytes(Parameter);
      }
      if (ScopeId.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(ScopeId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (FromId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(FromId);
      }
      if (toAddress_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ToAddress);
      }
      if (MethodName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(MethodName);
      }
      if (Parameter.Length != 0) {
        output.WriteRawTag(34);
        output.WriteBytes(Parameter);
      }
      if (ScopeId.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(ScopeId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (FromId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FromId);
      }
      if (toAddress_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ToAddress);
      }
      if (MethodName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MethodName);
      }
      if (Parameter.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Parameter);
      }
      if (ScopeId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ScopeId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ForwardInput other) {
      if (other == null) {
        return;
      }
      if (other.FromId.Length != 0) {
        FromId = other.FromId;
      }
      if (other.toAddress_ != null) {
        if (toAddress_ == null) {
          ToAddress = new global::AElf.Types.Address();
        }
        ToAddress.MergeFrom(other.ToAddress);
      }
      if (other.MethodName.Length != 0) {
        MethodName = other.MethodName;
      }
      if (other.Parameter.Length != 0) {
        Parameter = other.Parameter;
      }
      if (other.ScopeId.Length != 0) {
        ScopeId = other.ScopeId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            FromId = input.ReadString();
            break;
          }
          case 18: {
            if (toAddress_ == null) {
              ToAddress = new global::AElf.Types.Address();
            }
            input.ReadMessage(ToAddress);
            break;
          }
          case 26: {
            MethodName = input.ReadString();
            break;
          }
          case 34: {
            Parameter = input.ReadBytes();
            break;
          }
          case 42: {
            ScopeId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            FromId = input.ReadString();
            break;
          }
          case 18: {
            if (toAddress_ == null) {
              ToAddress = new global::AElf.Types.Address();
            }
            input.ReadMessage(ToAddress);
            break;
          }
          case 26: {
            MethodName = input.ReadString();
            break;
          }
          case 34: {
            Parameter = input.ReadBytes();
            break;
          }
          case 42: {
            ScopeId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ForwardRecord : pb::IMessage<ForwardRecord>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ForwardRecord> _parser = new pb::MessageParser<ForwardRecord>(() => new ForwardRecord());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ForwardRecord> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AElf.Contracts.Delegator.DelegatorContractReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ForwardRecord() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ForwardRecord(ForwardRecord other) : this() {
      fromId_ = other.fromId_;
      scopeId_ = other.scopeId_;
      virtualFromAddress_ = other.virtualFromAddress_ != null ? other.virtualFromAddress_.Clone() : null;
      toAddress_ = other.toAddress_ != null ? other.toAddress_.Clone() : null;
      methodName_ = other.methodName_;
      parameter_ = other.parameter_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ForwardRecord Clone() {
      return new ForwardRecord(this);
    }

    /// <summary>Field number for the "from_id" field.</summary>
    public const int FromIdFieldNumber = 1;
    private string fromId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FromId {
      get { return fromId_; }
      set {
        fromId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "scope_id" field.</summary>
    public const int ScopeIdFieldNumber = 2;
    private string scopeId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ScopeId {
      get { return scopeId_; }
      set {
        scopeId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "virtual_from_address" field.</summary>
    public const int VirtualFromAddressFieldNumber = 3;
    private global::AElf.Types.Address virtualFromAddress_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AElf.Types.Address VirtualFromAddress {
      get { return virtualFromAddress_; }
      set {
        virtualFromAddress_ = value;
      }
    }

    /// <summary>Field number for the "to_address" field.</summary>
    public const int ToAddressFieldNumber = 4;
    private global::AElf.Types.Address toAddress_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AElf.Types.Address ToAddress {
      get { return toAddress_; }
      set {
        toAddress_ = value;
      }
    }

    /// <summary>Field number for the "method_name" field.</summary>
    public const int MethodNameFieldNumber = 5;
    private string methodName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MethodName {
      get { return methodName_; }
      set {
        methodName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "parameter" field.</summary>
    public const int ParameterFieldNumber = 6;
    private pb::ByteString parameter_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Parameter {
      get { return parameter_; }
      set {
        parameter_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ForwardRecord);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ForwardRecord other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FromId != other.FromId) return false;
      if (ScopeId != other.ScopeId) return false;
      if (!object.Equals(VirtualFromAddress, other.VirtualFromAddress)) return false;
      if (!object.Equals(ToAddress, other.ToAddress)) return false;
      if (MethodName != other.MethodName) return false;
      if (Parameter != other.Parameter) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (FromId.Length != 0) hash ^= FromId.GetHashCode();
      if (ScopeId.Length != 0) hash ^= ScopeId.GetHashCode();
      if (virtualFromAddress_ != null) hash ^= VirtualFromAddress.GetHashCode();
      if (toAddress_ != null) hash ^= ToAddress.GetHashCode();
      if (MethodName.Length != 0) hash ^= MethodName.GetHashCode();
      if (Parameter.Length != 0) hash ^= Parameter.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (FromId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(FromId);
      }
      if (ScopeId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ScopeId);
      }
      if (virtualFromAddress_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(VirtualFromAddress);
      }
      if (toAddress_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(ToAddress);
      }
      if (MethodName.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(MethodName);
      }
      if (Parameter.Length != 0) {
        output.WriteRawTag(50);
        output.WriteBytes(Parameter);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (FromId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(FromId);
      }
      if (ScopeId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ScopeId);
      }
      if (virtualFromAddress_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(VirtualFromAddress);
      }
      if (toAddress_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(ToAddress);
      }
      if (MethodName.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(MethodName);
      }
      if (Parameter.Length != 0) {
        output.WriteRawTag(50);
        output.WriteBytes(Parameter);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (FromId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FromId);
      }
      if (ScopeId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ScopeId);
      }
      if (virtualFromAddress_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(VirtualFromAddress);
      }
      if (toAddress_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ToAddress);
      }
      if (MethodName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MethodName);
      }
      if (Parameter.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Parameter);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ForwardRecord other) {
      if (other == null) {
        return;
      }
      if (other.FromId.Length != 0) {
        FromId = other.FromId;
      }
      if (other.ScopeId.Length != 0) {
        ScopeId = other.ScopeId;
      }
      if (other.virtualFromAddress_ != null) {
        if (virtualFromAddress_ == null) {
          VirtualFromAddress = new global::AElf.Types.Address();
        }
        VirtualFromAddress.MergeFrom(other.VirtualFromAddress);
      }
      if (other.toAddress_ != null) {
        if (toAddress_ == null) {
          ToAddress = new global::AElf.Types.Address();
        }
        ToAddress.MergeFrom(other.ToAddress);
      }
      if (other.MethodName.Length != 0) {
        MethodName = other.MethodName;
      }
      if (other.Parameter.Length != 0) {
        Parameter = other.Parameter;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            FromId = input.ReadString();
            break;
          }
          case 18: {
            ScopeId = input.ReadString();
            break;
          }
          case 26: {
            if (virtualFromAddress_ == null) {
              VirtualFromAddress = new global::AElf.Types.Address();
            }
            input.ReadMessage(VirtualFromAddress);
            break;
          }
          case 34: {
            if (toAddress_ == null) {
              ToAddress = new global::AElf.Types.Address();
            }
            input.ReadMessage(ToAddress);
            break;
          }
          case 42: {
            MethodName = input.ReadString();
            break;
          }
          case 50: {
            Parameter = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            FromId = input.ReadString();
            break;
          }
          case 18: {
            ScopeId = input.ReadString();
            break;
          }
          case 26: {
            if (virtualFromAddress_ == null) {
              VirtualFromAddress = new global::AElf.Types.Address();
            }
            input.ReadMessage(VirtualFromAddress);
            break;
          }
          case 34: {
            if (toAddress_ == null) {
              ToAddress = new global::AElf.Types.Address();
            }
            input.ReadMessage(ToAddress);
            break;
          }
          case 42: {
            MethodName = input.ReadString();
            break;
          }
          case 50: {
            Parameter = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class IsPermittedAddressInput : pb::IMessage<IsPermittedAddressInput>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<IsPermittedAddressInput> _parser = new pb::MessageParser<IsPermittedAddressInput>(() => new IsPermittedAddressInput());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<IsPermittedAddressInput> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AElf.Contracts.Delegator.DelegatorContractReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IsPermittedAddressInput() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IsPermittedAddressInput(IsPermittedAddressInput other) : this() {
      toAddress_ = other.toAddress_ != null ? other.toAddress_.Clone() : null;
      scopeId_ = other.scopeId_;
      address_ = other.address_ != null ? other.address_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IsPermittedAddressInput Clone() {
      return new IsPermittedAddressInput(this);
    }

    /// <summary>Field number for the "to_address" field.</summary>
    public const int ToAddressFieldNumber = 1;
    private global::AElf.Types.Address toAddress_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AElf.Types.Address ToAddress {
      get { return toAddress_; }
      set {
        toAddress_ = value;
      }
    }

    /// <summary>Field number for the "scope_id" field.</summary>
    public const int ScopeIdFieldNumber = 2;
    private string scopeId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ScopeId {
      get { return scopeId_; }
      set {
        scopeId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "address" field.</summary>
    public const int AddressFieldNumber = 3;
    private global::AElf.Types.Address address_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AElf.Types.Address Address {
      get { return address_; }
      set {
        address_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as IsPermittedAddressInput);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(IsPermittedAddressInput other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(ToAddress, other.ToAddress)) return false;
      if (ScopeId != other.ScopeId) return false;
      if (!object.Equals(Address, other.Address)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (toAddress_ != null) hash ^= ToAddress.GetHashCode();
      if (ScopeId.Length != 0) hash ^= ScopeId.GetHashCode();
      if (address_ != null) hash ^= Address.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (toAddress_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ToAddress);
      }
      if (ScopeId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ScopeId);
      }
      if (address_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Address);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (toAddress_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ToAddress);
      }
      if (ScopeId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ScopeId);
      }
      if (address_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Address);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (toAddress_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ToAddress);
      }
      if (ScopeId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ScopeId);
      }
      if (address_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Address);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(IsPermittedAddressInput other) {
      if (other == null) {
        return;
      }
      if (other.toAddress_ != null) {
        if (toAddress_ == null) {
          ToAddress = new global::AElf.Types.Address();
        }
        ToAddress.MergeFrom(other.ToAddress);
      }
      if (other.ScopeId.Length != 0) {
        ScopeId = other.ScopeId;
      }
      if (other.address_ != null) {
        if (address_ == null) {
          Address = new global::AElf.Types.Address();
        }
        Address.MergeFrom(other.Address);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (toAddress_ == null) {
              ToAddress = new global::AElf.Types.Address();
            }
            input.ReadMessage(ToAddress);
            break;
          }
          case 18: {
            ScopeId = input.ReadString();
            break;
          }
          case 26: {
            if (address_ == null) {
              Address = new global::AElf.Types.Address();
            }
            input.ReadMessage(Address);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (toAddress_ == null) {
              ToAddress = new global::AElf.Types.Address();
            }
            input.ReadMessage(ToAddress);
            break;
          }
          case 18: {
            ScopeId = input.ReadString();
            break;
          }
          case 26: {
            if (address_ == null) {
              Address = new global::AElf.Types.Address();
            }
            input.ReadMessage(Address);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class IsPermittedMethodInput : pb::IMessage<IsPermittedMethodInput>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<IsPermittedMethodInput> _parser = new pb::MessageParser<IsPermittedMethodInput>(() => new IsPermittedMethodInput());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<IsPermittedMethodInput> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AElf.Contracts.Delegator.DelegatorContractReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IsPermittedMethodInput() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IsPermittedMethodInput(IsPermittedMethodInput other) : this() {
      toAddress_ = other.toAddress_ != null ? other.toAddress_.Clone() : null;
      scopeId_ = other.scopeId_;
      methodName_ = other.methodName_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IsPermittedMethodInput Clone() {
      return new IsPermittedMethodInput(this);
    }

    /// <summary>Field number for the "to_address" field.</summary>
    public const int ToAddressFieldNumber = 1;
    private global::AElf.Types.Address toAddress_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AElf.Types.Address ToAddress {
      get { return toAddress_; }
      set {
        toAddress_ = value;
      }
    }

    /// <summary>Field number for the "scope_id" field.</summary>
    public const int ScopeIdFieldNumber = 2;
    private string scopeId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ScopeId {
      get { return scopeId_; }
      set {
        scopeId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "method_name" field.</summary>
    public const int MethodNameFieldNumber = 3;
    private string methodName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MethodName {
      get { return methodName_; }
      set {
        methodName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as IsPermittedMethodInput);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(IsPermittedMethodInput other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(ToAddress, other.ToAddress)) return false;
      if (ScopeId != other.ScopeId) return false;
      if (MethodName != other.MethodName) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (toAddress_ != null) hash ^= ToAddress.GetHashCode();
      if (ScopeId.Length != 0) hash ^= ScopeId.GetHashCode();
      if (MethodName.Length != 0) hash ^= MethodName.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (toAddress_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ToAddress);
      }
      if (ScopeId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ScopeId);
      }
      if (MethodName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(MethodName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (toAddress_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ToAddress);
      }
      if (ScopeId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ScopeId);
      }
      if (MethodName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(MethodName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (toAddress_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ToAddress);
      }
      if (ScopeId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ScopeId);
      }
      if (MethodName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MethodName);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(IsPermittedMethodInput other) {
      if (other == null) {
        return;
      }
      if (other.toAddress_ != null) {
        if (toAddress_ == null) {
          ToAddress = new global::AElf.Types.Address();
        }
        ToAddress.MergeFrom(other.ToAddress);
      }
      if (other.ScopeId.Length != 0) {
        ScopeId = other.ScopeId;
      }
      if (other.MethodName.Length != 0) {
        MethodName = other.MethodName;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (toAddress_ == null) {
              ToAddress = new global::AElf.Types.Address();
            }
            input.ReadMessage(ToAddress);
            break;
          }
          case 18: {
            ScopeId = input.ReadString();
            break;
          }
          case 26: {
            MethodName = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (toAddress_ == null) {
              ToAddress = new global::AElf.Types.Address();
            }
            input.ReadMessage(ToAddress);
            break;
          }
          case 18: {
            ScopeId = input.ReadString();
            break;
          }
          case 26: {
            MethodName = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
