// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: financing_contract.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using System.Collections.Generic;
using aelf = global::AElf.CSharp.Core;

namespace Tank.Contracts.Financing {

  #region Events
  public partial class ApplyPassed : aelf::IEvent<ApplyPassed>
  {
    public global::System.Collections.Generic.IEnumerable<ApplyPassed> GetIndexed()
    {
      return new List<ApplyPassed>
      {
      };
    }

    public ApplyPassed GetNonIndexed()
    {
      return new ApplyPassed
      {
        EnterpriseName = EnterpriseName,
        Organization = Organization,
        ProductName = ProductName,
        Allowance = Allowance,
        Apy = Apy,
        Period = Period,
        ApplyStatus = ApplyStatus,
        GuaranteeMethod = GuaranteeMethod,
        ApplyTime = ApplyTime,
        PassedTime = PassedTime,
      };
    }
  }

  #endregion
  public static partial class FinancingContractContainer
  {
    static readonly string __ServiceName = "FinancingContract";

    #region Marshallers
    static readonly aelf::Marshaller<global::Tank.Contracts.Financing.InitializeInput> __Marshaller_InitializeInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Tank.Contracts.Financing.InitializeInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Tank.Contracts.Financing.ResetDelegatorInput> __Marshaller_ResetDelegatorInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Tank.Contracts.Financing.ResetDelegatorInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Types.Address> __Marshaller_aelf_Address = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Types.Address.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Tank.Contracts.Financing.EnterpriseBasicInfo> __Marshaller_EnterpriseBasicInfo = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Tank.Contracts.Financing.EnterpriseBasicInfo.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Tank.Contracts.Financing.EnterpriseFurtherInfo> __Marshaller_EnterpriseFurtherInfo = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Tank.Contracts.Financing.EnterpriseFurtherInfo.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Tank.Contracts.Financing.ApplyInput> __Marshaller_ApplyInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Tank.Contracts.Financing.ApplyInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Tank.Contracts.Financing.CancelInput> __Marshaller_CancelInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Tank.Contracts.Financing.CancelInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Tank.Contracts.Financing.AddFinancingProductInput> __Marshaller_AddFinancingProductInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Tank.Contracts.Financing.AddFinancingProductInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Tank.Contracts.Financing.RemoveFinancingProductInput> __Marshaller_RemoveFinancingProductInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Tank.Contracts.Financing.RemoveFinancingProductInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Tank.Contracts.Financing.SetAllowanceInput> __Marshaller_SetAllowanceInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Tank.Contracts.Financing.SetAllowanceInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Tank.Contracts.Financing.ApproveInput> __Marshaller_ApproveInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Tank.Contracts.Financing.ApproveInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Tank.Contracts.Financing.ApproveAllowanceInput> __Marshaller_ApproveAllowanceInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Tank.Contracts.Financing.ApproveAllowanceInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Tank.Contracts.Financing.ConfirmCertificateInput> __Marshaller_ConfirmCertificateInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Tank.Contracts.Financing.ConfirmCertificateInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.StringValue> __Marshaller_google_protobuf_StringValue = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.StringValue.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Tank.Contracts.Financing.AddressList> __Marshaller_AddressList = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Tank.Contracts.Financing.AddressList.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Tank.Contracts.Financing.FinancingProductList> __Marshaller_FinancingProductList = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Tank.Contracts.Financing.FinancingProductList.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Tank.Contracts.Financing.EnterpriseInfo> __Marshaller_EnterpriseInfo = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Tank.Contracts.Financing.EnterpriseInfo.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Tank.Contracts.Financing.GetApplyRecordInput> __Marshaller_GetApplyRecordInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Tank.Contracts.Financing.GetApplyRecordInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Tank.Contracts.Financing.ApplyRecord> __Marshaller_ApplyRecord = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Tank.Contracts.Financing.ApplyRecord.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Tank.Contracts.Financing.GetApplyRecordListInput> __Marshaller_GetApplyRecordListInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Tank.Contracts.Financing.GetApplyRecordListInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Tank.Contracts.Financing.ApplyRecordList> __Marshaller_ApplyRecordList = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Tank.Contracts.Financing.ApplyRecordList.Parser.ParseFrom);
    #endregion

    #region Methods
    static readonly aelf::Method<global::Tank.Contracts.Financing.InitializeInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Initialize = new aelf::Method<global::Tank.Contracts.Financing.InitializeInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Initialize",
        __Marshaller_InitializeInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Tank.Contracts.Financing.ResetDelegatorInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ResetDelegator = new aelf::Method<global::Tank.Contracts.Financing.ResetDelegatorInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "ResetDelegator",
        __Marshaller_ResetDelegatorInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ChangeOwner = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "ChangeOwner",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Tank.Contracts.Financing.EnterpriseBasicInfo, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Certificate = new aelf::Method<global::Tank.Contracts.Financing.EnterpriseBasicInfo, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Certificate",
        __Marshaller_EnterpriseBasicInfo,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Tank.Contracts.Financing.EnterpriseFurtherInfo, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Complete = new aelf::Method<global::Tank.Contracts.Financing.EnterpriseFurtherInfo, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Complete",
        __Marshaller_EnterpriseFurtherInfo,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Tank.Contracts.Financing.ApplyInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Apply = new aelf::Method<global::Tank.Contracts.Financing.ApplyInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Apply",
        __Marshaller_ApplyInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Tank.Contracts.Financing.CancelInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Cancel = new aelf::Method<global::Tank.Contracts.Financing.CancelInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Cancel",
        __Marshaller_CancelInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Tank.Contracts.Financing.AddFinancingProductInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_AddFinancingProduct = new aelf::Method<global::Tank.Contracts.Financing.AddFinancingProductInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "AddFinancingProduct",
        __Marshaller_AddFinancingProductInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Tank.Contracts.Financing.RemoveFinancingProductInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RemoveFinancingProduct = new aelf::Method<global::Tank.Contracts.Financing.RemoveFinancingProductInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "RemoveFinancingProduct",
        __Marshaller_RemoveFinancingProductInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Tank.Contracts.Financing.SetAllowanceInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetAllowance = new aelf::Method<global::Tank.Contracts.Financing.SetAllowanceInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetAllowance",
        __Marshaller_SetAllowanceInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Tank.Contracts.Financing.ApproveInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_OnlineApprove = new aelf::Method<global::Tank.Contracts.Financing.ApproveInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "OnlineApprove",
        __Marshaller_ApproveInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Tank.Contracts.Financing.ApproveInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_OfflineApprove = new aelf::Method<global::Tank.Contracts.Financing.ApproveInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "OfflineApprove",
        __Marshaller_ApproveInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Tank.Contracts.Financing.ApproveAllowanceInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ApproveAllowance = new aelf::Method<global::Tank.Contracts.Financing.ApproveAllowanceInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "ApproveAllowance",
        __Marshaller_ApproveAllowanceInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Tank.Contracts.Financing.ConfirmCertificateInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ConfirmCertificate = new aelf::Method<global::Tank.Contracts.Financing.ConfirmCertificateInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "ConfirmCertificate",
        __Marshaller_ConfirmCertificateInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RemoveEnterpriseInfo = new aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "RemoveEnterpriseInfo",
        __Marshaller_google_protobuf_StringValue,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Tank.Contracts.Financing.AddressList> __Method_GetAdminAddressList = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Tank.Contracts.Financing.AddressList>(
        aelf::MethodType.View,
        __ServiceName,
        "GetAdminAddressList",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_AddressList);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Tank.Contracts.Financing.AddressList> __Method_GetEnterpriseAddressList = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Tank.Contracts.Financing.AddressList>(
        aelf::MethodType.View,
        __ServiceName,
        "GetEnterpriseAddressList",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_AddressList);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Tank.Contracts.Financing.AddressList> __Method_GetOrganizationAddressList = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Tank.Contracts.Financing.AddressList>(
        aelf::MethodType.View,
        __ServiceName,
        "GetOrganizationAddressList",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_AddressList);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Tank.Contracts.Financing.FinancingProductList> __Method_GetFinancingProductList = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Tank.Contracts.Financing.FinancingProductList>(
        aelf::MethodType.View,
        __ServiceName,
        "GetFinancingProductList",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_FinancingProductList);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Tank.Contracts.Financing.EnterpriseInfo> __Method_GetEnterpriseInfo = new aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Tank.Contracts.Financing.EnterpriseInfo>(
        aelf::MethodType.View,
        __ServiceName,
        "GetEnterpriseInfo",
        __Marshaller_google_protobuf_StringValue,
        __Marshaller_EnterpriseInfo);

    static readonly aelf::Method<global::Tank.Contracts.Financing.GetApplyRecordInput, global::Tank.Contracts.Financing.ApplyRecord> __Method_GetApplyRecord = new aelf::Method<global::Tank.Contracts.Financing.GetApplyRecordInput, global::Tank.Contracts.Financing.ApplyRecord>(
        aelf::MethodType.View,
        __ServiceName,
        "GetApplyRecord",
        __Marshaller_GetApplyRecordInput,
        __Marshaller_ApplyRecord);

    static readonly aelf::Method<global::Tank.Contracts.Financing.GetApplyRecordListInput, global::Tank.Contracts.Financing.ApplyRecordList> __Method_GetApplyRecordList = new aelf::Method<global::Tank.Contracts.Financing.GetApplyRecordListInput, global::Tank.Contracts.Financing.ApplyRecordList>(
        aelf::MethodType.View,
        __ServiceName,
        "GetApplyRecordList",
        __Marshaller_GetApplyRecordListInput,
        __Marshaller_ApplyRecordList);

    #endregion

    #region Descriptors
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Tank.Contracts.Financing.FinancingContractReflection.Descriptor.Services[0]; }
    }

    public static global::System.Collections.Generic.IReadOnlyList<global::Google.Protobuf.Reflection.ServiceDescriptor> Descriptors
    {
      get
      {
        return new global::System.Collections.Generic.List<global::Google.Protobuf.Reflection.ServiceDescriptor>()
        {
          global::Tank.Contracts.Financing.FinancingContractReflection.Descriptor.Services[0],
        };
      }
    }
    #endregion
  }
}
#endregion

